### PR TITLE
Fix system font loading in Pango

### PR DESCRIPTION
**Pull request by bratsche**
In VSMac we currently can't display San Francisco fonts. This patch fixes it.

This fixes bug #1048838

### CODE REVIEW

**Comment by sevoku** [comment]
This should be backported to 6.8 (2019-10) for MonoDevelop 8.5 and if possible also to 6.6 (2019-08) for MonoDevelop 8.4 servicing.

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-12
@monojenkins backport 2019-10

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-08

**Comment by akoeplinger** [comment]
I got approval from Marek Safar on Slack to backport to 2019-08.

**Pull request merged**
