### PR TITLE
[gtk-sharp] Bump to pick up a build fix

### PR DESCRIPTION
**Pull request by radical**
Fix from https://github.com/mono/gtk-sharp/pull/264

### CODE REVIEW

**Comment by akoeplinger** [comment]
This is bumping to master branch while we should be using gtk-sharp-2-12-branch according to the file.

Can you cherry-pick your fix to that branch?

**Comment by akoeplinger** [comment]
Ah wait, the commit you're adding here was actually based on the 2-12 branch but it only got merged into master so this commit is dangling. We should get it into 2-12.

**Comment by radical** [comment]
@akoeplinger thanks! Opened: https://github.com/mono/gtk-sharp/pull/264 .

**Comment by radical** [comment]
@akoeplinger @Therzok Reference updated

**Comment by radical** [comment]
thanks!

**Pull request merged**
