### PR TITLE
Refactored patches for added safety

### PR DESCRIPTION
**Pull request by alexanderkyte**
Make patching a separate step, track patches as a seperate class and create a seperate list of them to apply after fetching to avoid array indexing errors.

### CODE REVIEW

**Comment by DavidNielsen** [comment]
Speaking as a casual Bockbuild user I really like this as it makes the default case easier to express. My assumption here of course is that the default is a simple package whch needs a little patch to build. This is often relevant e.g. for adding a MacPort patch.

Currently this means we have to transform the beautiful, easy to read base Package into an abomination.

Package ('name', 'version', sources = ['https://www.awesome.me/${name}/${name}-%{version}.tar.xz'])

becomes:

class NamePackage (Package):
	def __init__ (self):
		Package.__init__ (self, 'name', 'version',
			sources = ['https://www.awesome.me/${name}/${name}-%{version}.tar.xz']

		if Package.profile.name == 'darwin':
			self.sources.extend ([
				# Fix compile on OS X
				'https://www.dispicable.me/brainwashing.patch'
				])

	def prep (self):
		Package.prep (self)
		if Package.profile.name == 'darwin':
			for p in range (1, len (self.sources)):
				self.sh ('patch -p0 --ignore-whitespace < "%{sources[' + str (p) + ']}"')
NamePackage ()

which to me feels like an awful lot of ugly to add just to get what in my experience is a common case handled.

As for your approach I find that invoking Patch() repeatedly feels.. Odd.

Ideally I'd like to see the packaging format to be as close to:

Package ('name', 'version', sources = ['https://www.awesome.me/${name}/${name}-%{version}.tar.xz'])

Patch ([
'patch1',
'patch2': 'p1'
])

For a simple example with patches applied.

Thoughts?

**Comment by alexischr** [comment]
You're right that having Patch class take multiple patch files would be
more elegant, and this should be trivial to add, though I feel for @kyte
since he just fixed-up all packages and we didn't think about it beforehand
:)

**Comment by DavidNielsen** [comment]
So long as you guys make it so the package definitions can be as beautiful and simple as described above I will personally update every single package to adopt the new style.

I already did version and syntax bumps for pretty much everything as part of the Banshee GSoC prep in a fork and I have minions who can be appropriately whipped if we lack.. Well lackeys.

**Comment by alexanderkyte** [comment]
@DavidNielsen how does that look? Your syntax above isn't valid python(having key/value in an array) but I added a class that would allow 

sources.append(Patches([
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
'http://foo.bar.com/patch'
], shared_options = "-p0"))

which just translates the .run () call to the patches that it contains internally.

**Comment by akoeplinger** [comment]
Should we revive this now that we've transitioned Mono over to using the public bockbuild repo?

**Comment by alexischr** [comment]
Yes we should revive this/keep this open, we still need to make patching nice. Half of this looks like it holds today, but the fetch/prep/build flow has changed quite a bit since this pull request so there's some work needed to merge.

**Comment by akoeplinger** [comment]
I don't think we'll spend time on this given the current state of things, closing :)

**Pull request closed without merging**
